### PR TITLE
Use DB to look up items instead of STAC url

### PR DESCRIPTION
**Pull request by moradology**
## Description

This PR modifies the `MultiBaseTilerFactory` from `TiTiler` so that the starlette `Request` object is included as a dependency of tiler endpoints. Having access to the request object allows the database connection pool to be accessed so that items can be looked up and materialized in the tiler without making a call to the STAC api itself.

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Tiler endpoints have been used in the dev environment to ensure no loss of functionality after the change.

## Checklist:

Please delete options that are not relevant.

- [x] I have performed a self-review
- [x] Changelog has been updated
- [x] Unit tests pass locally (./scripts/test)
- [x] Code is linted and styled (./scripts/format)

### CODE REVIEW

**Comment by moradology** [comment]
Racking my brain right now trying to figure out what's going on with the search test failures. It looks as though `limit` is being ignored whenever item IDs are included in the search. What's odd is that the relevant bits of code weren't changed at all and inspecting the `PCSearch` object and its values reveals that `limit` appears to be set as expected when `_search_base` is called. Maybe the switch from `pypgstac` 0.4.3 to 0.4.5 is at issue?

**Comment by vincentsarago** [comment]
👋 @moradology

sorry you were `Racking` your brain on this. I implemented something similar in https://github.com/developmentseed/eoAPI/pull/31

1. **Custom DatasetPathParam**

Because the `pool` is available in the request object (https://github.com/microsoft/planetary-computer-apis/blob/main/pctiler/pctiler/main.py#L89-L98) we can add it in the [ItemPathParam](https://github.com/microsoft/planetary-computer-apis/blob/main/pctiler/pctiler/endpoints/item.py#L27-L33)

```python
import json
from typing import Dict
from cachetools import LRUCache, cached
from cachetools.keys import hashkey

from fastapi import Query
from starlette.requests import Request

def ItemPathParams(
    request: Request,
    collection: str = Query(..., description="STAC Collection ID"),
    item: str = Query(..., description="STAC Item ID"),
) -> Dict:
    return get_item(
        request.app.state.dbpool,
        collection,
        item,
    )

# I think caching is important because we don't want the tiler to hit the db on each tile request
@cached(
    LRUCache(maxsize=512),
    key=lambda pool, collection, item: hashkey(collection, item),
)
def get_item(pool, collection, item):
    """Get STAC Item from PGStac."""
    req = dict(
        filter={
            "op": "and",
            "args": [
                {
                    "op": "eq",
                    "args": [{"property": "collection"}, collection],
                },
                {"op": "eq", "args": [{"property": "id"}, item]},
            ],
        },
    )
    with pool.connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute(
                "SELECT * FROM search(%s);",
                (json.dumps(req),),
            )
            resp = cursor.fetchone()[0]
            features = resp.get("features", [])
            if not len(features):
                raise Exception(
                    "No item '{item}' found in '{collection}' collection"
                )

            return features[0]
```

Note: In this case the output of `ItemPathParams` will be a Dict (while the STACReader expect a str) so we need to create a custom STACRearder

2. **Custom STACReader**

see https://github.com/developmentseed/eoAPI/blob/master/src/eoapi/raster/eoapi/raster/reader.py#L1-L69

Note: this needs to be updated with https://github.com/microsoft/planetary-computer-apis/blob/main/pctiler/pctiler/reader.py#L35-L49


Let me know if you want some help with this 🙏

**Comment by moradology** [comment]
Hey @vincentsarago! Thank you for the tips. One quick question (maybe more to follow): The `ItemPathParams` seem like an obvious win here in terms of simplifying some of the code in `factory.py`, but rewriting the calls to reader as is done [here](https://github.com/microsoft/planetary-computer-apis/pull/55/files#diff-3d9f966962c7c0c58475af962b57fa58bf144ea2016e8b52e6469e3bf19bf232R56-R60) will still be necessary if I'm reading your suggestions correctly, right?

**Comment by vincentsarago** [comment]
@moradology 😄 

> but rewriting the calls to reader as is done [here](https://github.com/microsoft/planetary-computer-apis/pull/55/files#diff-3d9f966962c7c0c58475af962b57fa58bf144ea2016e8b52e6469e3bf19bf232R56-R60) will still be necessary if I'm reading your suggestions correctly, right?

yes we need a custom reader because the `path_dependency` (ItemPathParams) will now return a Dict whereas the `regular` STACReader expect a string as input.

**Comment by moradology** [comment]
Closing, as superseded by #62

**Pull request closed without merging**
